### ISSUE TITLE
Где travis ci и codecov?

### ISSUE THREAD

**Issue by coursar** [taxa222/SportmasterBonus#2]

**Comment by taxa222** [comment]
@coursar  процент покрытия 0.81 не проходит Travis CI ( Failing)

**Comment by taxa222** [comment]
@coursar пофиксил в aa0b843c6768557d781b52e221869767f26bebf4 теперь покрытие 95%,   Travis CI не проходит

**Comment by taxa222** [comment]
@coursar все готово codecov -81%

**Comment by coursar** [comment]
Если готово - закрывайте issue
