### ISSUE TITLE
Оформление кода

### ISSUE THREAD

**Issue by coursar** [taxa222/SportmasterBonus#3]
https://github.com/taxa222/SportmasterBonus/blob/09cf15f1ce978a6ffc1726e0e2c03cd70e33dbfa/src/main/java/ru/itpark/CalculateBonus.java#L22-L32

1. Используйте return сразу в if
1. Всегда используйте для if и else фигурные скобки

**Comment by taxa222** [comment]
Исправлено в  5081d82bed8edb195716d4f853b15256ed95293a

**Comment by taxa222** [comment]
@coursar  Исправлено в 5081d82bed8edb195716d4f853b15256ed95293a

**Comment by coursar** [comment]
Если исправили - закрывайте. Желательно сразу закрывать сообщением коммита.
