### ISSUE TITLE
Что проверяет этот тест?

### ISSUE THREAD

**Issue by coursar** [taxa222/SportmasterBonus#4]
https://github.com/taxa222/SportmasterBonus/blob/09cf15f1ce978a6ffc1726e0e2c03cd70e33dbfa/src/test/java/ru/itpark/CalculateBonusTest.java#L9-L25

**Comment by taxa222** [comment]
@coursar  На самом неделе ничего , Исправлено в e4eda7a3c3c307ba5fd6b1c9839e999ed81b920c

**Comment by taxa222** [comment]
@coursar пофиксил в aa0b843c6768557d781b52e221869767f26bebf4

**Comment by coursar** [comment]
Если сделали - закрывайте таску, не нужно переназначать на меня
